# Generated by Django 6.0.2 on 2026-04-09 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='website',
        ),
    ]
