# Generated by Django 6.0.2 on 2026-04-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_remove_brand_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
